import type { LevelConfig } from '@/types/game'

export const LEVELS: Record<number, LevelConfig> = {
  1: {
    name: 'OUTSKIRTS',
    env: 'Outskirts',
    muni: 54,
    wind: false,
    drones: 0,
    ew: 0,
    soldiers: 0,
    reds: 3,
    shelters: 2,
    win: 'targets',
    brief: 'Iron Grid forward camp detected. Destroy all targets to soften the perimeter.',
    clear: 'Perimeter cleared. The resistance moves into the outer fields.',
  },
  2: {
    name: 'WINDY VALLEY',
    env: 'Windy Valley',
    muni: 58,
    wind: true,
    drones: 1,
    ew: 0,
    soldiers: 5,
    reds: 2,
    shelters: 1,
    win: 'shelters85',
    brief: 'Crosswinds rip through the valley. Compensate your munition trajectory. Destroy 85% of shelters.',
    clear: 'The valley bunkers crumble. Supply lines to the Grid are severed.',
  },
  3: {
    name: 'IRON CITY',
    env: 'Iron City',
    muni: 40,
    wind: true,
    drones: 3,
    ew: 1,
    soldiers: 7,
    reds: 7,
    shelters: 0,
    win: 'dronesbunkers',
    brief: 'Automated interceptor drones now hunt you. Eliminate enemy drones AND bunkers.',
    clear: 'Iron City sky is ours. Interceptor swarm neutralized.',
  },
  4: {
    name: 'THE DEAD ZONE',
    env: 'The Dead Zone',
    muni: 62,
    wind: true,
    drones: 5,
    ew: 3,
    soldiers: 9,
    reds: 3,
    shelters: 0,
    win: 'ewtargets',
    brief: 'РЕБ jamming towers scramble your systems. Destroy EW towers, then clear all targets.',
    clear: 'Jamming nets down. Signal restored. The Dead Zone is silent.',
  },
  5: {
    name: 'KREMLIN PALACE',
    env: 'Kremlin Palace',
    muni: 74,
    wind: true,
    drones: 7,
    ew: 4,
    soldiers: 3,
    reds: 3,
    shelters: 0,
    win: 'devilmouth',
    brief: 'The Swine Overlord rules from behind iron walls. Only his open face is vulnerable — fly into the red barriers and he will chew you apart!',
    clear: '',
  },
}
